# Generated by Django 4.2 on 2023-05-02 18:27

import core.utils.file_path
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('upload', models.FileField(upload_to=core.utils.file_path.upload_documentos, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['txt'])], verbose_name='Document')),
                ('status', models.CharField(choices=[('1', 'Pendente'), ('2', 'Processando'), ('3', 'Processado')], default='1', max_length=1)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contract',
                'verbose_name_plural': 'Contracts',
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Seller name')),
                ('role', models.CharField(max_length=20, verbose_name='Seller role')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SmallIntegerField()),
                ('description', models.CharField(max_length=20, verbose_name='Description')),
                ('nature', models.CharField(choices=[('Entrada', 'Entrada'), ('Saida', 'Saída')], default='Entrada', max_length=20)),
                ('signal', models.CharField(choices=[('+', '+'), ('-', '-')], default=' ', max_length=1)),
            ],
            options={
                'verbose_name': 'TransactionType',
                'verbose_name_plural': 'TransactionTypes',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('product', models.CharField(max_length=30, verbose_name='product')),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('seller', models.CharField(blank=True, max_length=20, null=True, verbose_name='seller')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactio_contract', to='transactions.contract')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transaction_type', to='transactions.transactiontype')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['type'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_data', models.JSONField(verbose_name='report data')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='report', to='transactions.contract')),
            ],
            options={
                'verbose_name': 'report',
                'verbose_name_plural': 'reports',
            },
        ),
    ]
