# Generated by Django 4.2 on 2023-05-02 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seller',
        ),
    ]
