# Generated by Django 4.2 on 2023-04-26 18:31

import core.utils.file_path
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('type', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=20, verbose_name='Description')),
                ('nature', models.CharField(choices=[('Entrada', 'Entrada'), ('Saida', 'Saída')], default='Entrada', max_length=20)),
                ('signal', models.CharField(choices=[('+', '+'), ('-', '-')], default=' ', max_length=1)),
            ],
            options={
                'verbose_name': 'TransactionType',
                'verbose_name_plural': 'TransactionTypes',
            },
        ),
        migrations.AlterField(
            model_name='contract',
            name='upload',
            field=models.FileField(upload_to=core.utils.file_path.upload_documentos, verbose_name='Document'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('product', models.CharField(max_length=30, verbose_name='product')),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('seller', models.CharField(blank=True, max_length=20, null=True, verbose_name='seller')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='transactions.transactiontype')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
    ]
