# Generated by Django 4.2 on 2023-04-26 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_contract_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('1', 'Pendente'), ('2', 'Processando'), ('3', 'Processado')], default='1', max_length=1),
        ),
    ]
