# Generated by Django 4.2 on 2023-05-03 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_delete_seller'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ['-id'], 'verbose_name': 'Contract', 'verbose_name_plural': 'Contracts'},
        ),
    ]
