# Generated by Django 4.2 on 2023-04-26 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_seller_transaction_contract_alter_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiontype',
            name='mapper',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
