# Generated by Django 4.2 on 2023-05-01 07:21

import core.utils.file_path
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_contract_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='role',
            field=models.CharField(default=0, max_length=20, verbose_name='Seller role'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contract',
            name='upload',
            field=models.FileField(upload_to=core.utils.file_path.upload_documentos, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['txt'])], verbose_name='Document'),
        ),
    ]
