# Generated by Django 4.2 on 2023-05-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_contract_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='price',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='seller',
            field=models.CharField(default=1, max_length=20, verbose_name='seller'),
            preserve_default=False,
        ),
    ]
