# Generated by Django 4.2 on 2023-05-01 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_seller_role_alter_contract_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='balance',
        ),
    ]
