# Generated by Django 4.2 on 2023-05-03 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_transaction_price_alter_transaction_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiontype',
            name='nature',
            field=models.CharField(choices=[('Entrada', 'Entrada'), ('Saida', 'Saída'), ('ERROR', 'ERROR')], default='Entrada', max_length=20),
        ),
        migrations.AlterField(
            model_name='transactiontype',
            name='signal',
            field=models.CharField(choices=[('+', '+'), ('-', '-'), ('X', 'X')], default=' ', max_length=1),
        ),
    ]
