# Generated by Django 4.2 on 2023-05-01 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_remove_seller_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.BigIntegerField(default=0, verbose_name='balance')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='transactions.contract')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='transactions.seller')),
            ],
            options={
                'verbose_name': 'report',
                'verbose_name_plural': 'reports',
            },
        ),
    ]
