# Generated by Django 4.2 on 2023-05-01 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='report',
            name='seller',
        ),
        migrations.AddField(
            model_name='report',
            name='report_data',
            field=models.JSONField(default=1, verbose_name='report data'),
            preserve_default=False,
        ),
    ]
