# Generated by Django 4.2 on 2023-05-03 10:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(error_messages='You must provide a valid email address', max_length=255, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
